// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK3yUP7XjPSLcSiSO0aIWddJS8WiPldJc',
    appId: '1:368946897111:web:20d910cad9a7784bb15092',
    messagingSenderId: '368946897111',
    projectId: 'vynl-b454c',
    authDomain: 'vynl-b454c.firebaseapp.com',
    databaseURL: 'https://vynl-b454c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vynl-b454c.firebasestorage.app',
    measurementId: 'G-5W4J83R5DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI43vaZ3IJ9ZPxiss8_DVMHkkOiR96KJ8',
    appId: '1:368946897111:android:afc4688e8518ade2b15092',
    messagingSenderId: '368946897111',
    projectId: 'vynl-b454c',
    databaseURL: 'https://vynl-b454c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vynl-b454c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK3yUP7XjPSLcSiSO0aIWddJS8WiPldJc',
    appId: '1:368946897111:web:11bfe34626a0f81eb15092',
    messagingSenderId: '368946897111',
    projectId: 'vynl-b454c',
    authDomain: 'vynl-b454c.firebaseapp.com',
    databaseURL: 'https://vynl-b454c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vynl-b454c.firebasestorage.app',
    measurementId: 'G-9TXGN8FXRG',
  );
}
